Re-add quotes around shape prose including commas
This broke my database import:

```
psycopg2.DataError: extra data after last expected column
CONTEXT:  COPY pokemon_shape_prose, line 21: "6,9,Upright,Sciurine,Pokémon with a bipedal, tailed form"
```